#!/usr/bin/env bun
/**
 * シングルバイナリのビルド（SPEC §12.1）。
 * 1. SPA をビルド（dist/）
 * 2. ターゲット用の sqlite-vec プリビルドを vendor/ に用意
 * 3. src/generated/embedded.ts を生成（dist アセット + vec 拡張を埋め込み import）
 * 4. bun build --compile
 * 5. embedded.ts をスタブへ復元
 *
 * 使い方: bun run scripts/compile.ts [--target bun-darwin-arm64] [--outfile path]
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { parseArgs } from "node:util";
import { VENDOR_TARGETS, vendorLibPath } from "./fetch-vendor";

const root = join(import.meta.dir, "..");
const GENERATED = join(root, "src", "generated", "embedded.ts");

const STUB = `// scripts/compile.ts がコンパイル時に上書きする埋め込みアセット表。
// 開発時（bun run）はこのスタブのまま = 埋め込みなしで、dist/ と node_modules から解決する。

/** SPA アセット: URL パス → バイナリ埋め込みファイルのパス */
export const embeddedAssets: Record<string, string> = {};

/** sqlite-vec 拡張の埋め込みパス（null なら node_modules から解決） */
export const embeddedVecLib: string | null = null;

/** 展開先ファイル名（vec0.dylib / vec0.so / vec0.dll） */
export const embeddedVecLibName = "";
`;

function currentBunTarget(): string {
  const os = process.platform === "win32" ? "windows" : process.platform;
  return `bun-${os}-${process.arch}`;
}

function run(cmd: string[], env?: Record<string, string>): void {
  console.error(`$ ${cmd.join(" ")}`);
  const proc = Bun.spawnSync(cmd, {
    cwd: root,
    env: { ...process.env, ...env },
    stdout: "inherit",
    stderr: "inherit",
  });
  if (proc.exitCode !== 0) {
    throw new Error(`command failed (${proc.exitCode}): ${cmd.join(" ")}`);
  }
}

function generateEmbeddedModule(bunTarget: string): void {
  const distDir = join(root, "dist");
  const assets = readdirSync(distDir).filter((f) => !f.endsWith(".map"));
  const vecLib = vendorLibPath(bunTarget);
  if (!existsSync(vecLib)) throw new Error(`vendor library not found: ${vecLib}`);

  const lines: string[] = [
    "// generated by scripts/compile.ts — DO NOT EDIT (restored to stub after compile)",
  ];
  assets.forEach((file, i) => {
    lines.push(`import asset${i} from "../../dist/${file}" with { type: "file" };`);
  });
  const vecRel = relative(join(root, "src", "generated"), vecLib).replaceAll("\\", "/");
  lines.push(`import vecLib from "${vecRel}" with { type: "file" };`);
  lines.push("");
  lines.push("export const embeddedAssets: Record<string, string> = {");
  assets.forEach((file, i) => {
    lines.push(`  "/${file}": asset${i},`);
  });
  lines.push("};");
  lines.push("");
  lines.push("export const embeddedVecLib: string | null = vecLib;");
  lines.push(`export const embeddedVecLibName = ${JSON.stringify(vecLib.split("/").pop())};`);
  lines.push("");
  writeFileSync(GENERATED, lines.join("\n"));
}

if (import.meta.main) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      target: { type: "string" },
      outfile: { type: "string" },
    },
  });
  const bunTarget = values.target ?? currentBunTarget();
  if (!VENDOR_TARGETS.some((t) => t.bunTarget === bunTarget)) {
    throw new Error(
      `unsupported target: ${bunTarget} (supported: ${VENDOR_TARGETS.map((t) => t.bunTarget).join(", ")})`,
    );
  }
  const outfile = values.outfile ?? join(root, "kura");

  run(["bun", "run", "scripts/build-html.ts"]);
  run(["bun", "run", "scripts/fetch-vendor.ts", bunTarget]);

  const backup = readFileSync(GENERATED, "utf-8");
  try {
    generateEmbeddedModule(bunTarget);
    run([
      "bun",
      "build",
      "src/cli/index.ts",
      "--compile",
      `--target=${bunTarget}`,
      "--minify-whitespace",
      "--minify-syntax",
      `--outfile=${outfile}`,
    ]);
  } finally {
    // スタブに復元（backup が既に生成物だった場合もスタブへ戻す）
    writeFileSync(GENERATED, backup.includes("DO NOT EDIT") ? STUB : backup);
  }
  console.error(`compiled: ${outfile} (${bunTarget})`);
}
