#!/usr/bin/env bun
/**
 * Single-binary build (docs: build-and-release.md).
 * 1. Build the SPA (dist/)
 * 2. Place the sqlite-vec prebuilt for the target under vendor/
 * 3. Generate src/generated/embedded.ts (embedding dist assets + the vec extension via imports)
 * 4. bun build --compile
 * 5. Restore embedded.ts to the stub
 *
 * Usage: bun run scripts/compile.ts [--target bun-darwin-arm64] [--outfile path]
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { parseArgs } from "node:util";
import { VENDOR_TARGETS, vendorLibPath } from "./fetch-vendor";

const root = join(import.meta.dir, "..");
const GENERATED = join(root, "src", "generated", "embedded.ts");

const STUB = `// Embedded asset table, overwritten by scripts/compile.ts at compile time.
// During development (bun run) this stub stays as-is = nothing embedded; assets resolve from dist/ and node_modules.

/** SPA assets: URL path → path of the file embedded in the binary */
export const embeddedAssets: Record<string, string> = {};

/** Embedded path of the sqlite-vec extension (null = resolve from node_modules) */
export const embeddedVecLib: string | null = null;

/** Extraction file name (vec0.dylib / vec0.so / vec0.dll) */
export const embeddedVecLibName = "";
`;

function currentBunTarget(): string {
  const os = process.platform === "win32" ? "windows" : process.platform;
  return `bun-${os}-${process.arch}`;
}

function run(cmd: string[], env?: Record<string, string>): void {
  console.error(`$ ${cmd.join(" ")}`);
  const proc = Bun.spawnSync(cmd, {
    cwd: root,
    env: { ...process.env, ...env },
    stdout: "inherit",
    stderr: "inherit",
  });
  if (proc.exitCode !== 0) {
    throw new Error(`command failed (${proc.exitCode}): ${cmd.join(" ")}`);
  }
}

function generateEmbeddedModule(bunTarget: string): void {
  const distDir = join(root, "dist");
  const assets = readdirSync(distDir).filter((f) => !f.endsWith(".map"));
  const vecLib = vendorLibPath(bunTarget);
  if (!existsSync(vecLib)) throw new Error(`vendor library not found: ${vecLib}`);

  const lines: string[] = [
    "// generated by scripts/compile.ts — DO NOT EDIT (restored to stub after compile)",
  ];
  assets.forEach((file, i) => {
    lines.push(`import asset${i} from "../../dist/${file}" with { type: "file" };`);
  });
  const vecRel = relative(join(root, "src", "generated"), vecLib).replaceAll("\\", "/");
  lines.push(`import vecLib from "${vecRel}" with { type: "file" };`);
  lines.push("");
  lines.push("export const embeddedAssets: Record<string, string> = {");
  assets.forEach((file, i) => {
    lines.push(`  "/${file}": asset${i},`);
  });
  lines.push("};");
  lines.push("");
  lines.push("export const embeddedVecLib: string | null = vecLib;");
  lines.push(`export const embeddedVecLibName = ${JSON.stringify(vecLib.split("/").pop())};`);
  lines.push("");
  writeFileSync(GENERATED, lines.join("\n"));
}

if (import.meta.main) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      target: { type: "string" },
      outfile: { type: "string" },
    },
  });
  const bunTarget = values.target ?? currentBunTarget();
  if (!VENDOR_TARGETS.some((t) => t.bunTarget === bunTarget)) {
    throw new Error(
      `unsupported target: ${bunTarget} (supported: ${VENDOR_TARGETS.map((t) => t.bunTarget).join(", ")})`,
    );
  }
  const outfile = values.outfile ?? join(root, "kura");

  run(["bun", "run", "scripts/build-html.ts"]);
  run(["bun", "run", "scripts/fetch-vendor.ts", bunTarget]);

  const backup = readFileSync(GENERATED, "utf-8");
  try {
    generateEmbeddedModule(bunTarget);
    run([
      "bun",
      "build",
      "src/cli/index.ts",
      "--compile",
      `--target=${bunTarget}`,
      "--minify-whitespace",
      "--minify-syntax",
      `--outfile=${outfile}`,
    ]);
  } finally {
    // Restore the stub (also fall back to the stub if the backup was itself a generated file)
    writeFileSync(GENERATED, backup.includes("DO NOT EDIT") ? STUB : backup);
  }
  console.error(`compiled: ${outfile} (${bunTarget})`);
}
